### ISSUE TITLE
panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by jeff-cook** [raffis/renovate-metrics#29]
I get the following error whenever I run renovate-metrics on a log file with more then 1 repo in it.  

> panic: duplicate metrics collector registration attempted

I have tried with and without

- logFormat=json
- logContext=renovate

I have tried with v0.0.4, v0.0.5 and latest

Renovate version 
- Many version of 37
- renovate/renovate:37.426.4

I'm not sure what else to try. 

I really look forward to using this tool.

Thanks

**Comment by ced455** [comment]
Hello, I have the same issue. on my case it look like it happen when i run renovate on multiple repos.

If i split the log file for each repo then I don't get the error.

**Comment by raffis** [comment]
There was a fix by @Obito1903 in https://github.com/raffis/renovate-metrics/pull/27 which might resolve your problem. This was included in v0.0.6,
