### ISSUE TITLE
Toggleable Metrics/Labels

### ISSUE THREAD

**Issue by nhandler** [raffis/renovate-metrics#54]
When running Renovate against a large number of repositories, it can lead to rather high cardinality in the metrics that are being produced by renovate-metrics. This is due to the many labels with a potentially infinite set of values. It would be nice if there was a way to toggle certain metrics/labels off to help reduce the number of metrics.

**Comment by raffis** [comment]
I don't think it make sense to support this. If you really want to ignore certain metrics you should drop them at scrape time by using metrics relabeling.
